"""Offline structural checks for a channel-template bundle.

`popcorn flow validate` is the authority on whether a single flow's references
resolve, but it needs a channel and a live server, and it only ever sees one
file at a time. The defects this module exists for are the ones that span files,
or that every layer below accepts in silence:

- a fixture named `.yaml`, which the importer installs as a flow
- two files whose basenames collide once the zip is flattened
- a write to a column the manifest does not declare (the store accepts it and
  produces a column no reference can reach)
- an `output_schema` property that a later step dereferences but that is not
  listed in `required`, so the model may legally omit it
- a schedule or webhook naming a flow the bundle does not contain

None of those are bad references, so none of them fail validation. All of them
were live failures while the alerttracker bundle was written; see
`examples/alerttracker/GOTCHAS.md`.

To answer any of that it has to model the DSL's SHAPE — which is not the same as
modelling its catalog. It knows that a step is exactly one of `activity`,
`sleep_seconds`, `await_approval` or a nested `steps:` block; that a block's
inner ids are private and only its `outputs:` keys escape; that `collect:`
publishes a second readable name beside `output`; that a numeric path segment is
an array index; that `$trigger` carries a closed set of keys. It does not know
what any activity takes or returns, which is the server's to own.

Every one of those rules it READS rather than restates. They come from
`popcorn_core.flow_rules`, a snapshot of `GET /customer-flows/schema`
regenerated by `scripts/sync_flow_rules.py`, so this module still imports
nothing but stdlib and that snapshot and still needs no server. Hand-copying
them is what let the reference grammar here accept `$a..b` while the
interpreter rejected it, and let `max_block_depth` go unenforced entirely.

The one thing it deliberately does NOT model is `when:`. That grammar has four
rails routed legacy-first, and mirroring the routing offline means
reimplementing the predicate parser — so `when:` gets its references checked and
its grammar left alone. A near-miss reimplementation is worse than no check: the
rule this module used to enforce ("exactly one `==`/`!=`, no boolean operators")
described a grammar the engine never had, and rejected 55 valid clauses across
the five templates the platform ships.

Every finding is a `Finding(level, code, where, message)`. The codes are a
stable contract: CI and agents branch on them, so rename one only with a
version bump.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from popcorn_core import flow_rules

ERROR = "error"
WARNING = "warning"

# Filenames no reader ever installs as a flow: the manifest and its legacy
# alias, plus the three reserved documents. One set rather than the importer's
# two, because every use site here asks the same question — is this `.yaml` a
# flow candidate at all.
RESERVED_FILENAMES = frozenset(
    {
        *flow_rules.MANIFEST_FILENAMES,
        flow_rules.AGENT_DOC_FILENAME,
        flow_rules.README_FILENAME,
        flow_rules.STRINGS_FILENAME,
    }
)

# Subdirectories the tree reader descends into, seeding a channel parameter
# from each. The zip reader preserves the same one segment instead of
# flattening it to a basename, which is the only classification rule the two
# readers agree on.
PRESERVED_DIRS = frozenset(flow_rules.SUBDIRS)

# The triggering context the interpreter seeds under `$trigger`. A closed set,
# so a typo in it is checkable — unlike `$channel`, whose keys come from a
# per-channel config the bundle cannot see.
TRIGGER_KEYS = frozenset(flow_rules.TRIGGER_KEYS)

# A reference is the whole string value, `$` then a root then an optional
# dotted path. The server reported `malformed reference '$row.Last Seen'` for a
# value containing a space, which is how we know it takes the entire string
# rather than interpolating a prefix out of it. Two groups, so `_ref_parts`
# rejoins them into whole segments.
_REF_RE = re.compile(flow_rules.REFERENCE_PATTERN)

# The failure a step absorbed under `on_error: skip`, readable as
# `$steps.<id>.error` and null when the step did not fail. Every step carries
# it, so unlike `output` and a `collect:` name there is nothing per-step to
# consult. Both properties are strings, so nothing is reachable below them.
# Mirrors popcorn-backend: lib/temporal/dsl/validator.py — _STEP_ERROR_SCHEMA.
#
# Hand-authored, which is the bug this was added for: the served schema carries
# the reference grammar but not the per-step head rule, so `make check-rules`
# cannot see a head the backend adds. Moving the head list into the payload is
# tracked on KEW-2331.
_STEP_ERROR_PROPERTIES = ("message", "type")


# `$channel` keys the interpreter seeds itself, so the manifest never declares
# them: the connected-integrations map and the same integrations as a list to
# fan out over.
_CHANNEL_RUNTIME_KEYS = frozenset({"integrations", "integration_list"})

# Quoted literals inside a `when:` expression, stripped before scanning for
# refs so `$a == '$literal'` does not report a reference to `$literal`.
_QUOTED_RE = re.compile(r"'[^']*'|\"[^\"]*\"")

# Any `$ref` embedded in a larger string. Used ONLY for `when:`, which is the
# one place a reference is not the whole value.
_EMBEDDED_REF_RE = re.compile(r"\$[A-Za-z_][A-Za-z0-9_.]*")


# Activities whose args name a table and carry column names as keys.
_WRITE_ACTIVITIES = {
    "foundation.store.upsert_rows": "rows",
    "foundation.store.insert_rows": "rows",
    "foundation.store.patch_row": "patch",
}
_READ_ACTIVITIES = frozenset(
    {
        "foundation.store.list_rows",
        "foundation.store.get_row",
        "foundation.store.delete_row",
    }
)

# Activities that declare their result shape at the call site, making
# `$steps.<id>.output.<prop>` statically checkable.
_SCHEMA_ACTIVITIES = frozenset(
    {
        "foundation.agent.transform",
        "foundation.fields.extract",
    }
)


@dataclass(frozen=True)
class Finding:
    """One structural defect. `where` is bundle-relative, or 'bundle'."""

    level: str
    code: str
    where: str
    message: str

    def __str__(self) -> str:
        return f"{self.level} {self.code} [{self.where}]: {self.message}"


@dataclass
class Flow:
    """A parsed flow file, keyed by the `name:` inside it, not its filename."""

    path: str
    name: str
    doc: dict[str, Any]

    @property
    def steps(self) -> list[dict[str, Any]]:
        raw = self.doc.get("steps")
        return [s for s in raw if isinstance(s, dict)] if isinstance(raw, list) else []


@dataclass(frozen=True)
class _StepInfo:
    """What a completed step publishes, from the reader's point of view.

    Three mutually exclusive shapes, because the DSL has three: a plain step
    publishes `output`; a foreach with `collect: <name>` also publishes that
    name; a block publishes ONLY the keys in its `outputs:` map.
    """

    collect: str | None = None
    schema: dict[str, set[str]] | None = None
    published: set[str] | None = None


@dataclass
class _Scope:
    """What references may name at one point in a flow.

    A block's inner steps see the enclosing scope, but its inner ids are
    private to it — so scopes nest rather than accumulate, and `child()` is
    what keeps an inner id from leaking out.
    """

    inputs: set[str] = field(default_factory=set)
    integrations: set[str] = field(default_factory=set)
    steps: dict[str, _StepInfo] = field(default_factory=dict)
    items: set[str] = field(default_factory=set)

    def child(self) -> _Scope:
        return _Scope(
            inputs=self.inputs,
            integrations=self.integrations,
            steps=dict(self.steps),
            items=set(self.items),
        )


@dataclass
class BundleReport:
    directory: str
    flows: list[Flow] = field(default_factory=list)
    fixtures: list[str] = field(default_factory=list)
    manifest: dict[str, Any] | None = None
    findings: list[Finding] = field(default_factory=list)

    @property
    def errors(self) -> list[Finding]:
        return [f for f in self.findings if f.level == ERROR]

    @property
    def warnings(self) -> list[Finding]:
        return [f for f in self.findings if f.level == WARNING]

    @property
    def ok(self) -> bool:
        return not self.errors

    def to_dict(self) -> dict[str, Any]:
        return {
            "directory": self.directory,
            "ok": self.ok,
            "flows": [{"name": f.name, "file": f.path} for f in self.flows],
            "fixtures": self.fixtures,
            "has_manifest": self.manifest is not None,
            "findings": [
                {"level": f.level, "code": f.code, "where": f.where, "message": f.message}
                for f in self.findings
            ],
            "error_count": len(self.errors),
            "warning_count": len(self.warnings),
        }


class _Checker:
    def __init__(self, directory: Path) -> None:
        self.dir = directory
        self.report = BundleReport(directory=str(directory))
        self._prompt_stems: set[str] = set()
        self._template_stems: set[str] = set()

    # ── finding helpers ───────────────────────────────────────────────

    def err(self, code: str, where: str, message: str) -> None:
        self.report.findings.append(Finding(ERROR, code, where, message))

    def warn(self, code: str, where: str, message: str) -> None:
        self.report.findings.append(Finding(WARNING, code, where, message))

    # ── entry point ───────────────────────────────────────────────────

    def run(self) -> BundleReport:
        files = self._collect_files()
        self._check_collisions(files)
        self._check_nesting(files)
        self._check_code_blocks(files)
        self._load_manifest()
        self._load_flows(files)
        self._check_manifest_references()
        for flow in self.report.flows:
            self._check_flow(flow)
        self._check_scalar_collisions()
        return self.report

    # ── file layout ───────────────────────────────────────────────────

    def _collect_files(self) -> list[Path]:
        """Every entry the importer would see, in bundle order."""
        out: list[Path] = []
        for path in sorted(self.dir.rglob("*")):
            if not path.is_file():
                continue
            rel = path.relative_to(self.dir)
            # read_zip skips dotfiles and __MACOSX before anything else.
            if any(part.startswith(".") or part == "__MACOSX" for part in rel.parts):
                continue
            size = path.stat().st_size
            if size > flow_rules.MAX_ENTRY_BYTES:
                self.err(
                    "entry-too-large",
                    str(rel),
                    f"{size} bytes exceeds the importer's per-entry cap of "
                    f"{flow_rules.MAX_ENTRY_BYTES} bytes; the entry is rejected.",
                )
                continue
            # Exactly one segment under the subdir, not merely somewhere below
            # it: the tree reader tests the segment count, so `prompts/a/b.md`
            # is ignored rather than nested deeper. Reading it as a prompt here
            # would tell an author `$channel.prompts.b` resolves when nothing
            # ever seeds it.
            if _is_subdir_file(rel, "prompts"):
                self._prompt_stems.add(_file_key(path.name))
            elif _is_subdir_file(rel, "templates"):
                self._template_stems.add(_file_key(path.name))
            elif path.suffix == ".json":
                self.report.fixtures.append(str(rel))
            out.append(path)
        return out

    def _importer_key(self, path: Path) -> str:
        """What the entry is called after read_zip flattens the zip.

        Everything collapses to its basename except entries under `prompts/`
        or `templates/`, whose one path segment is preserved.

        Deliberately not gated on `SUBDIR_PATH_DEPTH`. That rule describes the
        TREE reader, and the endpoint publishes it for that reader only —
        read_zip keeps the leading segment at any depth, so `prompts/a/b.md`
        becomes `prompts/b.md` here and can collide with a real `prompts/b.md`.

        A code path keeps its WHOLE path instead, so two blocks never collide.
        The flattening model does not apply to it in either reader: the tree
        reader addresses a block file by its full path under `code/<block>/`,
        and read_zip installs flows and seeds `prompts/`/`templates/` — a
        `.py` is not an entry it keys at all. Modelling it as a collision made
        `template check` reject every bundle with two Python blocks, since the
        runner's convention requires each of them to carry `main.py`.
        """
        rel = path.relative_to(self.dir)
        if _under_code_dir(rel):
            return str(rel)
        if rel.parts[0] in PRESERVED_DIRS and len(rel.parts) > 1:
            return f"{rel.parts[0]}/{path.name}"
        return path.name

    def _check_code_blocks(self, files: list[Path]) -> None:
        """A path under `code/` the tree reader would not read.

        Publish REFUSES a tree containing one — an unread path would otherwise
        mint a version whose digest covers bytes the installer never looks at
        — so these are errors, not warnings. They are the only findings the
        code rule adds; everything else it changed was a false positive being
        removed.

        Note what cannot be reported here: a hidden entry under a block
        (`code/calc/.env`) also gets the tree refused, but `_collect_files`
        drops every dotted path before this runs, so the checker never sees
        one. That is the same filter `popcorn app publish` applies when it
        reads a working copy, so a bundle this command calls clean is one the
        CLI would not have uploaded the hidden file from anyway.
        """
        for path in files:
            rel = path.relative_to(self.dir)
            if not _under_code_dir(rel) or _code_block(rel) is not None:
                continue
            if len(rel.parts) < flow_rules.CODE_MIN_PATH_DEPTH:
                self.err(
                    "code-file-outside-block",
                    str(rel),
                    f"'{rel}' sits directly under {flow_rules.CODE_SUBDIR}/ rather than "
                    f"inside a block directory. Code ships one directory per block "
                    f"({flow_rules.CODE_SUBDIR}/<block>/…), and publish refuses a tree "
                    "carrying a path the installer would never read.",
                )
            elif not re.match(flow_rules.CODE_BLOCK_NAME_PATTERN, rel.parts[1]):
                # Tested explicitly rather than as an `else`: a bad segment
                # BELOW the block also lands here, and reporting that as a bad
                # block name would send an author to the wrong path segment.
                self.err(
                    "code-block-name-invalid",
                    str(rel),
                    f"'{rel.parts[1]}' is not a usable block name. It rides inside flow "
                    "YAML as `code_name:` and through error messages, so it must be a "
                    "slug — lowercase letters, digits, underscore and hyphen, starting "
                    "with a letter or digit. Publish refuses the tree otherwise.",
                )

    def _check_nesting(self, files: list[Path]) -> None:
        """A flow in a subdirectory means two different things, silently.

        The two readers disagree, and neither says so. The registry reads a
        template off disk and descends `prompts/` and `templates/` ONLY, so
        `flows/a.yaml` is not read at all — the flow just is not there. The zip
        reader flattens it to `a.yaml` and installs it. So the same bundle
        either has the flow or does not, depending on how it got in.

        Warning rather than error: a flat bundle is the only layout with one
        meaning, but nesting is legal and works under the zip reader.
        """
        if not flow_rules.FLOWS_AT_ROOT_ONLY:
            return  # the readers agree; there is nothing to disagree about
        for path in files:
            rel = path.relative_to(self.dir)
            if len(rel.parts) == 1 or path.suffix not in flow_rules.FLOW_SUFFIXES:
                continue
            if rel.parts[0] in PRESERVED_DIRS:
                continue
            # A `.yaml` under a code block is block source — a fixture the
            # block reads — not a flow the registry failed to find.
            if _under_code_dir(rel):
                continue
            self.warn(
                "nested-flow-file",
                str(rel),
                f"'{rel}' is in a subdirectory. The registry reader descends only "
                f"{'/, '.join(sorted(PRESERVED_DIRS))}/ and would not see this flow at all; "
                f"the zip reader would flatten it to '{path.name}'. Move it to the bundle root.",
            )

    def _check_collisions(self, files: list[Path]) -> None:
        """Two entries flattening to one name: the later silently wins."""
        seen: dict[str, list[str]] = {}
        for path in files:
            seen.setdefault(self._importer_key(path), []).append(str(path.relative_to(self.dir)))
        for key, paths in sorted(seen.items()):
            if len(paths) > 1:
                self.err(
                    "basename-collision",
                    ", ".join(paths),
                    f"{len(paths)} entries flatten to '{key}'. The importer keys by basename, "
                    "so only the last one survives — the others are silently dropped.",
                )

    # ── manifest ──────────────────────────────────────────────────────

    def _load_manifest(self) -> None:
        path = self.dir / "manifest.yaml"
        if not path.is_file():
            return
        doc = self._parse_yaml(path)
        if doc is None:
            return
        if not isinstance(doc, dict):
            self.err("manifest-not-a-mapping", "manifest.yaml", "Manifest must be a YAML mapping.")
            return
        self.report.manifest = doc
        if not doc.get("app_type"):
            self.warn(
                "clears-app-type",
                "manifest.yaml",
                "No app_type declared. Installing this bundle CLEARS the channel's app_type, "
                "which changes the client's whole interface paradigm. Intentional for an "
                "untyped ops bundle; never import it into a channel running a real app.",
            )
        self._check_tables(doc)

    def _columns(self, table: Any) -> list[dict[str, Any]]:
        if not isinstance(table, dict):
            return []
        raw = table.get("columns")
        return [c for c in raw if isinstance(c, dict)] if isinstance(raw, list) else []

    def _table_columns(self) -> dict[str, dict[str, dict[str, Any]]]:
        """`{table_name: {column_name: column_def}}` from the manifest."""
        tables = (self.report.manifest or {}).get("tables")
        if not isinstance(tables, dict):
            return {}
        out: dict[str, dict[str, dict[str, Any]]] = {}
        for name, table in tables.items():
            cols = {}
            for col in self._columns(table):
                col_name = col.get("name")
                if isinstance(col_name, str):
                    cols[col_name] = col
            out[str(name)] = cols
        return out

    def _check_tables(self, manifest: dict[str, Any]) -> None:
        tables = manifest.get("tables")
        if not isinstance(tables, dict):
            return
        for table_name, table in tables.items():
            where = f"manifest.yaml:tables.{table_name}"
            cols = {}
            for col in self._columns(table):
                name = col.get("name")
                if not isinstance(name, str):
                    self.err("column-without-name", where, "A column declaration has no `name`.")
                    continue
                cols[name] = col
                if col.get("merge") == "concat" and col.get("type") != "string":
                    self.err(
                        "concat-requires-string",
                        where,
                        f"Column '{name}' is merge:concat but type:{col.get('type')}. "
                        "Concat appends to a string; it cannot accumulate onto another type.",
                    )
            self._check_merge_key(table, cols, where)

    def _check_merge_key(self, table: Any, cols: dict[str, dict[str, Any]], where: str) -> None:
        """merge_key columns must be indexed and string-typed.

        The OR-probe behind `any_of` only queries the text index, so a
        non-string or unindexed merge key never matches and every upsert
        inserts a new row instead of merging.
        """
        merge_key = table.get("merge_key") if isinstance(table, dict) else None
        if not isinstance(merge_key, dict):
            return
        any_of = merge_key.get("any_of")
        if not isinstance(any_of, list):
            return
        for name in any_of:
            col = cols.get(str(name))
            if col is None:
                self.err(
                    "merge-key-unknown-column",
                    where,
                    f"merge_key.any_of names '{name}', which is not a declared column.",
                )
                continue
            if col.get("type") != "string":
                self.err(
                    "merge-key-not-string",
                    where,
                    f"merge_key column '{name}' is type:{col.get('type')}. The OR-probe only "
                    "queries the text index, so a non-string key silently never matches.",
                )
            if not (col.get("unique") or col.get("indexed")):
                self.err(
                    "merge-key-not-indexed",
                    where,
                    f"merge_key column '{name}' is not indexed. Add `unique: true` — an "
                    "unindexed merge key silently never matches.",
                )

    def _check_manifest_references(self) -> None:
        """Schedules and webhooks address flows by `name:`, not by filename."""
        manifest = self.report.manifest
        if manifest is None:
            return
        names = {f.name for f in self.report.flows}

        schedules = manifest.get("schedules")
        if isinstance(schedules, list):
            for i, sched in enumerate(schedules):
                if not isinstance(sched, dict):
                    continue
                where = f"manifest.yaml:schedules.{i}"
                flow = sched.get("flow")
                if isinstance(flow, str) and flow not in names:
                    self.err(
                        "schedule-unknown-flow",
                        where,
                        f"Schedule targets flow '{flow}', which no flow in this bundle declares "
                        f"as its `name:`. Known: {', '.join(sorted(names)) or '(none)'}.",
                    )
                if not sched.get("interval") and not sched.get("cron"):
                    self.err(
                        "schedule-no-trigger",
                        where,
                        "Schedule has neither `interval:` nor `cron:`, so it can never fire.",
                    )
                # At MOST one, as well as at least one. A schedule spec
                # carrying both cadences has two, and the backend refuses
                # rather than guess which the author meant to keep — so
                # catching it here is the difference between a checker
                # finding and an install against a real channel failing.
                if sched.get("interval") and sched.get("cron"):
                    self.err(
                        "schedule-two-triggers",
                        where,
                        "Schedule declares both `interval:` and `cron:`. Exactly one "
                        "cadence is allowed — the installer cannot pick between them "
                        "and will refuse the schedule.",
                    )

        webhooks = manifest.get("webhooks")
        if isinstance(webhooks, list):
            for i, hook in enumerate(webhooks):
                if not isinstance(hook, dict):
                    continue
                flow = hook.get("flow")
                if isinstance(flow, str) and flow not in names:
                    self.err(
                        "webhook-unknown-flow",
                        f"manifest.yaml:webhooks.{i}",
                        f"Webhook targets flow '{flow}', which no flow in this bundle declares "
                        f"as its `name:`.",
                    )

    def _check_scalar_collisions(self) -> None:
        """A scalar a flow writes must not also be declared in the manifest.

        `scalars:` upserts on every install, so a declared key that a flow also
        writes is reset to its install-time value on each re-import.
        """
        manifest = self.report.manifest
        if manifest is None:
            return
        declared = manifest.get("scalars")
        if not isinstance(declared, dict):
            return
        for flow in self.report.flows:
            for step in flow.steps:
                if step.get("activity") != "foundation.store.set_scalar":
                    continue
                args = step.get("args")
                key = args.get("key") if isinstance(args, dict) else None
                if isinstance(key, str) and key in declared:
                    self.warn(
                        "runtime-state-in-scalars",
                        f"{flow.path}:{step.get('id')}",
                        f"This step writes scalar '{key}', which manifest.yaml also declares "
                        "under `scalars:`. Scalars UPSERT on every install, so re-importing "
                        "resets the value this flow maintains. Declare only install-time "
                        "configuration; let flows create their own runtime keys.",
                    )

    # ── flows ─────────────────────────────────────────────────────────

    def _parse_yaml(self, path: Path) -> Any:
        try:
            import yaml
        except ImportError as exc:  # pragma: no cover - dependency is declared
            raise RuntimeError("template checks require PyYAML") from exc
        rel = str(path.relative_to(self.dir))
        try:
            return yaml.safe_load(path.read_text())
        except yaml.YAMLError as exc:
            self.err("yaml-parse-error", rel, f"Not parseable as YAML: {exc}")
            return None

    def _load_flows(self, files: list[Path]) -> None:
        by_name: dict[str, list[str]] = {}
        for path in files:
            if path.suffix not in flow_rules.FLOW_SUFFIXES:
                continue
            rel = path.relative_to(self.dir)
            if path.name in RESERVED_FILENAMES:
                continue
            # Same reason as in `_check_nesting`: block source, not a flow.
            if _under_code_dir(rel):
                continue
            if rel.parts[0] in PRESERVED_DIRS and len(rel.parts) > 1:
                continue
            doc = self._parse_yaml(path)
            if doc is None:
                continue
            if not isinstance(doc, dict) or "name" not in doc or "steps" not in doc:
                in_fixtures = "fixtures" in rel.parts
                self.err(
                    "fixture-installed-as-flow" if in_fixtures else "yaml-is-not-a-flow",
                    str(rel),
                    "Every .yaml/.yml in the bundle that is not manifest/config/strings is "
                    "installed as a flow, and this file has no `name:`/`steps:`. "
                    + (
                        "Rename it to .json — fixtures are data, not flows."
                        if in_fixtures
                        else "Give it a `name:` and `steps:`, or change its extension."
                    ),
                )
                continue
            name = doc.get("name")
            if not isinstance(name, str) or not name:
                self.err("flow-without-name", str(rel), "Flow `name:` must be a non-empty string.")
                continue
            by_name.setdefault(name, []).append(str(rel))
            self.report.flows.append(Flow(path=str(rel), name=name, doc=doc))

        for name, paths in sorted(by_name.items()):
            if len(paths) > 1:
                self.err(
                    "duplicate-flow-name",
                    ", ".join(paths),
                    f"{len(paths)} files declare `name: {name}`. Flow identity is the name, not "
                    "the filename, so these upsert over each other and only one survives.",
                )

    def _check_flow(self, flow: Flow) -> None:
        steps = flow.steps
        if not steps:
            self.err("flow-without-steps", flow.path, "Flow declares no steps.")
            return

        inputs = flow.doc.get("inputs")
        integrations = flow.doc.get("required_integrations")
        scope = _Scope(
            inputs=set(inputs) if isinstance(inputs, dict) else set(),
            integrations=set(integrations) if isinstance(integrations, dict) else set(),
        )
        after = self._check_step_list(flow, steps, scope, prefix="", depth=1)

        # The flow's own `outputs:` resolve AFTER every step, so they read the
        # final scope — not the empty one the first step saw.
        outputs = flow.doc.get("outputs")
        if outputs is not None:
            for path, value in _walk_strings(outputs, "outputs"):
                self._check_value(value, f"{flow.path}:{path}", after)

    def _check_step_list(
        self, flow: Flow, steps: list[dict[str, Any]], outer: _Scope, prefix: str, depth: int
    ) -> _Scope:
        """Check one step list, threading lexical scope through it.

        Steps run in order, so each step sees only the ones before it. A block
        (`steps:`) is checked with the enclosing scope PLUS its earlier
        siblings — inner steps read the full outer scope — and its own inner
        ids are dropped afterwards, because they are private to the block. What
        the block contributes to the outer scope is its `outputs:` keys, and
        nothing else.

        `depth` counts this list, the flow's own being 1 — the same origin the
        DSL's own tree validator uses, which is what makes the nesting cap
        comparable to `MAX_BLOCK_DEPTH` without an off-by-one.
        """
        scope = outer.child()
        for index, step in enumerate(steps):
            step_id = step.get("id")
            label = step_id or f"steps.{index}"
            where = f"{flow.path}:{prefix}{label}"

            if not isinstance(step_id, str) or not step_id:
                self.err("step-without-id", where, "Every step needs an `id:`.")
            elif step_id in scope.steps:
                self.err(
                    "duplicate-step-id",
                    where,
                    f"Step id '{step_id}' is already used earlier in this scope; "
                    f"`$steps.{step_id}` becomes ambiguous.",
                )

            actions = [key for key in flow_rules.STEP_ACTIONS if step.get(key) is not None]
            if len(actions) != 1:
                self.err(
                    "step-without-action",
                    where,
                    "A step is exactly one of "
                    + ", ".join(f"`{key}:`" for key in flow_rules.STEP_ACTIONS)
                    + (f"; found {', '.join(actions)}." if actions else "; found none."),
                )

            # `foreach:` names the list, so it resolves in the scope BEFORE
            # this step — the alias cannot be in scope yet.
            if "foreach" in step:
                for path, value in _walk_strings(step["foreach"], "foreach"):
                    self._check_value(value, f"{where}.{path}", scope)

            inner = scope.child()
            if isinstance(step.get("as"), str):
                inner.items.add(step["as"])

            # On a foreach step `when:` is the PER-ITEM gate, evaluated once
            # per iteration with the alias bound — so `when: $p.apply` is not
            # only legal, it is the idiom for skipping individual items. On any
            # other step there is no alias and the two scopes are the same.
            when = step.get("when")
            if when is not None:
                gate = inner if "foreach" in step else scope
                for ref in _when_refs(str(when)):
                    self._check_value(ref, f"{where}.when", gate)

            if "args" in step:
                for path, value in _walk_strings(step["args"], "args"):
                    self._check_value(value, f"{where}.{path}", inner)

            block = step.get("steps")
            published: set[str] | None = None
            if isinstance(block, list):
                if depth >= flow_rules.MAX_BLOCK_DEPTH:
                    # The DSL's tree validator raises on the first such block,
                    # so this is an install-time failure, not a style note. The
                    # walk continues anyway: an author fixing a bundle wants
                    # every finding in one pass, not one per run.
                    self.err(
                        "block-too-deep",
                        where,
                        f"This step opens a `steps:` block at nesting depth {depth + 1}, past "
                        f"the maximum of {flow_rules.MAX_BLOCK_DEPTH}. The flow parses but the "
                        "DSL's own model validator rejects it, so the failure lands at install "
                        "rather than here. Lift the inner steps into a sibling block, or move "
                        "them into a separate flow.",
                    )
                nested = [s for s in block if isinstance(s, dict)]
                self._check_step_list(flow, nested, inner, prefix=f"{label}.", depth=depth + 1)
                published = self._check_block_outputs(flow, step, inner, nested, where)

            self._check_columns(flow, step, where)

            if isinstance(step_id, str) and step_id:
                scope.steps[step_id] = _StepInfo(
                    collect=step.get("collect") if isinstance(step.get("collect"), str) else None,
                    schema=self._step_schema(step),
                    published=published,
                )

        return scope

    def _check_block_outputs(
        self,
        flow: Flow,
        step: dict[str, Any],
        inner: _Scope,
        nested: list[dict[str, Any]],
        where: str,
    ) -> set[str]:
        """A block's `outputs:` map, resolved in the block's INNER scope.

        This is the seam that makes a block checkable at all. Everything inside
        is private; `outputs:` is the only thing the enclosing flow can read,
        so its keys are exactly what `$steps.<block>.output.*` may name — and
        its values are refs the inner steps must actually have produced.
        """
        outputs = step.get("outputs")
        if not isinstance(outputs, dict):
            return set()
        after = inner.child()
        for nested_step in nested:
            nested_id = nested_step.get("id")
            if isinstance(nested_id, str) and nested_id:
                collect = nested_step.get("collect")
                after.steps[nested_id] = _StepInfo(
                    collect=collect if isinstance(collect, str) else None,
                    schema=self._step_schema(nested_step),
                    published=None,
                )
        for path, value in _walk_strings(outputs, "outputs"):
            self._check_value(value, f"{where}.{path}", after)
        return set(outputs)

    def _step_schema(self, step: dict[str, Any]) -> dict[str, set[str]] | None:
        """`{"properties": {...}, "required": {...}}` for a call-site schema.

        Only activities that declare `output_schema` in their args produce a
        statically knowable shape; everything else stays unchecked.
        """
        if step.get("activity") not in _SCHEMA_ACTIVITIES:
            return None
        args = step.get("args")
        if not isinstance(args, dict):
            return None
        schema = args.get("output_schema")
        if not isinstance(schema, dict):
            return None
        props = schema.get("properties")
        required = schema.get("required")
        return {
            "properties": set(props) if isinstance(props, dict) else set(),
            "required": set(required) if isinstance(required, list) else set(),
        }

    # ── references ────────────────────────────────────────────────────

    def _check_value(self, value: str, where: str, scope: _Scope) -> None:
        if not value.startswith("$"):
            return
        if "[" in value or "]" in value:
            self.err(
                "bracket-index",
                where,
                f"'{value}' indexes with brackets. Arrays are indexed with dots — "
                f"'{value.replace('[', '.').replace(']', '')}' — and a bracket makes the whole "
                "reference a literal string.",
            )
            return
        match = _REF_RE.match(value)
        if match is None:
            if " " in value:
                self.err(
                    "space-in-reference",
                    where,
                    f"'{value}' contains a space. Every segment of a reference path starts with "
                    "a letter or underscore and carries only letters, digits and underscores, so "
                    "a column with a space in its name cannot be dereferenced — only written "
                    "(YAML key) or filtered on (JSON key). Rename the column to be space-free.",
                )
            else:
                self.err(
                    "malformed-reference",
                    where,
                    f"'{value}' is not a valid reference path. Each dot-separated segment must "
                    "start with a letter or underscore, so a trailing dot, a doubled dot or a "
                    "segment starting with a digit resolves as a literal string at runtime "
                    "instead of as a reference.",
                )
            return

        parts = _ref_parts(match)
        root = parts[0]

        # A foreach alias SHADOWS every global root — the interpreter resolves
        # aliases before `channel` and `trigger` precisely so `as: channel`
        # keeps working. Check it first for the same reason.
        if root in scope.items:
            return  # the item's shape is the iterated value; unknowable here
        if root == "inputs":
            self._check_input_ref(value, parts, where, scope)
        elif root == "steps":
            self._check_step_ref(value, parts, where, scope)
        elif root == "channel":
            self._check_channel_ref(value, parts, where, scope)
        elif root == "trigger":
            if len(parts) > 1 and parts[1] not in TRIGGER_KEYS:
                self.err(
                    "unknown-trigger-key",
                    where,
                    f"'{value}' reads '{parts[1]}', which the triggering context does not carry. "
                    f"Available: {', '.join(sorted(TRIGGER_KEYS))}.",
                )
        elif root in flow_rules.REFERENCE_ROOTS:
            # A root the platform serves that this checker has no model for.
            # Accept it: the root is real, and inventing a finding against a
            # reference that resolves is the failure mode this whole snapshot
            # exists to end. `test_flow_rules.py` fails on a new root, so the
            # gap gets closed deliberately rather than discovered by an author.
            return
        else:
            known = [*flow_rules.REFERENCE_ROOTS, *sorted(scope.items)]
            self.err(
                "unknown-reference-root",
                where,
                f"'{value}' starts from '${root}', which is not a reference root here. "
                f"Available: {', '.join('$' + k for k in known)}.",
            )

    def _check_input_ref(self, value: str, parts: list[str], where: str, scope: _Scope) -> None:
        if len(parts) < 2:
            self.err("malformed-reference", where, f"'{value}' names no input.")
        elif parts[1] not in scope.inputs:
            self.err(
                "undeclared-input",
                where,
                f"'{value}' reads input '{parts[1]}', which this flow does not declare. "
                f"Declared: {', '.join(sorted(scope.inputs)) or '(none)'}.",
            )
        elif len(parts) > 2:
            self.err(
                "object-input-subfield",
                where,
                f"'{value}' reaches into an input's sub-fields, which is statically "
                "unreachable — an input declaration cannot describe an object's properties. "
                "Get a typed shape first with foundation.fields.extract (when the fields are "
                "there) or foundation.agent.transform (when the answer must be derived).",
            )

    def _check_step_ref(self, value: str, parts: list[str], where: str, scope: _Scope) -> None:
        if len(parts) < 2:
            self.err("malformed-reference", where, f"'{value}' names no step.")
            return
        step_id = parts[1]
        info = scope.steps.get(step_id)
        if info is None:
            self.err(
                "unknown-step-reference",
                where,
                f"'{value}' refers to step '{step_id}', which is not defined earlier in this "
                f"scope. Steps run in order, and a block's inner ids are private to it. "
                f"Available: {', '.join(sorted(scope.steps)) or '(none)'}.",
            )
            return
        if len(parts) < 3:
            return  # `$steps.<id>` — the whole output, no path to check
        head = parts[2]
        if head == info.collect:
            return  # a foreach's collected list; per-item shape unknowable here
        if head == "error":
            self._check_step_error_ref(value, parts[3:], step_id, where)
            return
        if head != "output":
            available = "`output` or `error`" + (f", or `{info.collect}`" if info.collect else "")
            self.err(
                "step-ref-needs-output",
                where,
                f"'{value}' reads '{head}' off step '{step_id}', which publishes {available}. "
                "Any other name only resolves when the step declares it with `collect:`.",
            )
            return
        rest = parts[3:]
        if not rest:
            return
        if info.published is not None:
            if rest[0] not in info.published:
                self.err(
                    "unknown-block-output",
                    where,
                    f"'{value}' reads '{rest[0]}' off block '{step_id}', which publishes "
                    f"{', '.join(sorted(info.published)) or '(nothing)'}. Everything else inside "
                    "a block is private to it.",
                )
            return
        if info.schema is None or rest[0].isdigit():
            # A numeric segment is an array index (the interpreter's own rule),
            # and `properties` describes an object — there is nothing to match
            # it against.
            return
        prop = rest[0]
        if prop not in info.schema["properties"]:
            self.err(
                "unknown-output-property",
                where,
                f"'{value}' reads '{prop}', which step '{step_id}' does not declare in its "
                f"output_schema.properties. Declared: "
                f"{', '.join(sorted(info.schema['properties'])) or '(none)'}.",
            )
        elif prop not in info.schema["required"]:
            self.err(
                "output-property-not-required",
                where,
                f"'{value}' reads '{prop}', which is declared but NOT in "
                f"output_schema.required. A declared-but-optional property is genuinely optional, "
                "and a missing key is a hard ReferenceError that fails the run — `on_error` "
                "cannot rescue it, because resolution precedes invocation. Add it to `required`.",
            )

    def _check_step_error_ref(self, value: str, rest: list[str], step_id: str, where: str) -> None:
        """Check the path under `$steps.<id>.error`, which any step publishes."""
        if not rest:
            return  # the whole `{message, type}` object
        if rest[0] not in _STEP_ERROR_PROPERTIES:
            self.err(
                "unknown-step-error-property",
                where,
                f"'{value}' reads '{rest[0]}' off `$steps.{step_id}.error`, which carries "
                f"{' and '.join(f'`{p}`' for p in _STEP_ERROR_PROPERTIES)}.",
            )
        elif len(rest) > 1:
            self.err(
                "unknown-step-error-property",
                where,
                f"'{value}' reaches below `$steps.{step_id}.error.{rest[0]}`, which is a string.",
            )

    def _check_channel_ref(self, value: str, parts: list[str], where: str, scope: _Scope) -> None:
        if len(parts) < 2:
            self.err("malformed-reference", where, f"'{value}' names no channel key.")
            return
        key = parts[1]
        if key == "prompts":
            if len(parts) > 2 and parts[2] not in self._prompt_stems:
                self.err(
                    "unknown-prompt",
                    where,
                    f"'{value}' reads prompt '{parts[2]}', but no prompts/{parts[2]}.* exists "
                    "in the bundle.",
                )
            return
        if key == "templates":
            if len(parts) > 2 and parts[2] not in self._template_stems:
                self.err(
                    "unknown-template",
                    where,
                    f"'{value}' reads template '{parts[2]}', but no templates/{parts[2]}.* "
                    "exists in the bundle.",
                )
            return
        if key == "integrations":
            # Two declaration sites, and a bundle may legitimately use either.
            # A flow's own `required_integrations:` buys a pre-flight refusal to
            # start when the integration is unconnected. The manifest's
            # `connections[].config_name` buys the client binding the name on
            # the first connect click — which is why claimcoordinator declares
            # `leads_inbox` there and deliberately in no flow. Neither is wrong,
            # so neither is a finding; naming the integration NOWHERE is.
            if len(parts) > 2 and parts[2] not in (scope.integrations | self._manifest_names()):
                self.warn(
                    "undeclared-integration",
                    where,
                    f"'{value}' reads integration '{parts[2]}', which nothing in the bundle "
                    "declares — not this flow's `required_integrations:`, and not a manifest "
                    "`connections[].config_name`. Known: "
                    f"{', '.join(sorted(scope.integrations | self._manifest_names())) or '(none)'}"
                    ". Without a declaration the interpreter cannot refuse to start when the "
                    "integration is unconnected, so the flow fails mid-run instead.",
                )
            return
        if key in _CHANNEL_RUNTIME_KEYS:
            return
        manifest = self.report.manifest
        if manifest is None:
            return
        declared: set[str] = set()
        for section in ("channel_parameters", "scalars", "default_scalars"):
            block = manifest.get(section)
            if isinstance(block, dict):
                declared |= set(block)
        if key not in declared:
            self.warn(
                "undeclared-channel-key",
                where,
                f"'{value}' reads channel key '{key}', which the manifest does not declare under "
                "channel_parameters, scalars or default_scalars. Fine if a flow writes it at "
                "runtime; a typo otherwise.",
            )

    # ── column names ──────────────────────────────────────────────────

    def _manifest_names(self) -> set[str]:
        """Integration names the manifest's `connections:` block binds.

        `config_name` is the channel-config name a connection binds to, which
        is exactly what `$channel.integrations.<name>` reads. A connection
        without one names its own instances (repeatable slots like `gcal`,
        `gcal_2`), so the id doubles as the name.
        """
        manifest = self.report.manifest
        if manifest is None:
            return set()
        connections = manifest.get("connections")
        if not isinstance(connections, list):
            return set()
        names: set[str] = set()
        for entry in connections:
            if not isinstance(entry, dict):
                continue
            for key in ("config_name", "id"):
                value = entry.get(key)
                if isinstance(value, str) and value:
                    names.add(value)
        return names

    def _check_columns(self, flow: Flow, step: dict[str, Any], where: str) -> None:
        """Cross-check written/read column names against the manifest.

        The store accepts undeclared columns silently, producing a column no
        reference can reach, so a write to an unknown column is an error. Reads
        are warnings: a filter may legitimately target a column some other flow
        created at runtime.
        """
        activity = step.get("activity")
        args = step.get("args")
        if not isinstance(args, dict) or not isinstance(activity, str):
            return
        table_name = args.get("table_name")
        if not isinstance(table_name, str):
            return
        columns = self._table_columns().get(table_name)
        if columns is None:
            return

        def report(names: Any, level: str, code: str, kind: str) -> None:
            for name in names:
                if not isinstance(name, str) or name.startswith("_") or name in columns:
                    continue
                message = f"{kind} column '{name}' is not declared on table '{table_name}'. " + (
                    "The store accepts undeclared columns silently, producing a column no "
                    "$ref can reach."
                    if level == ERROR
                    else "A filter on a column that does not exist matches nothing, silently."
                )
                getattr(self, "err" if level == ERROR else "warn")(code, where, message)

        write_key = _WRITE_ACTIVITIES.get(activity)
        if write_key:
            payload = args.get(write_key)
            rows = payload if isinstance(payload, list) else [payload]
            for row in rows:
                if isinstance(row, dict):
                    report(row.keys(), ERROR, "undeclared-column", "Written")

        if activity in _READ_ACTIVITIES or write_key:
            filters = args.get("filter")
            if isinstance(filters, dict):
                report(filters.keys(), WARNING, "unknown-filter-column", "Filtered")
            dropped = args.get("drop_columns")
            if isinstance(dropped, list):
                report(dropped, WARNING, "unknown-drop-column", "Dropped")


def _ref_parts(match: re.Match[str]) -> list[str]:
    """A matched reference's whole segments, root first.

    The served grammar splits root from remainder into two groups so that each
    can carry its own rule — the root is a bare identifier, the remainder may
    hold dots — while the checker reasons in segments, so they get rejoined
    here. Group 2 is None for a bare `$root`.
    """
    root, rest = match.group(1), match.group(2)
    return [root, *(rest.split(".") if rest else [])]


def _is_subdir_file(rel: Path, subdir: str) -> bool:
    """Whether a bundle-relative path is a file the tree reader reads from `subdir`."""
    return rel.parts[0] == subdir and len(rel.parts) == flow_rules.SUBDIR_PATH_DEPTH


def _under_code_dir(rel: Path) -> bool:
    """Whether a bundle-relative path sits anywhere below the code directory.

    Not the same question as `_code_block(rel)`: a path can be under `code/`
    and still be one publish refuses. The checks that must not mistake a block
    file for something else — a nested flow, a basename collision — ask this,
    so a malformed code path draws its own finding rather than an unrelated
    one about flows.
    """
    return rel.parts[0] == flow_rules.CODE_SUBDIR


def _code_block(rel: Path) -> str | None:
    """The block a path belongs to, or None if it is not a legal block file.

    The whole rule, applied in the order the tree reader applies it: under the
    code directory, at least `CODE_MIN_PATH_DEPTH` segments, a block segment
    matching `CODE_BLOCK_NAME_PATTERN`, and every segment below the block
    matching `CODE_PATH_SEGMENT_PATTERN`.
    """
    parts = rel.parts
    if not _under_code_dir(rel) or len(parts) < flow_rules.CODE_MIN_PATH_DEPTH:
        return None
    if not re.match(flow_rules.CODE_BLOCK_NAME_PATTERN, parts[1]):
        return None
    if not all(re.match(flow_rules.CODE_PATH_SEGMENT_PATTERN, p) for p in parts[2:]):
        return None
    return parts[1]


def _file_key(filename: str) -> str:
    """The config key a prompts/ or templates/ file is read by.

    `Path.stem` strips one suffix, so `compose_chase.md.j2` becomes
    `compose_chase.md` and never matches `$channel.prompts.compose_chase`.
    Longest suffix first, so `.md.j2` wins over `.j2`.
    """
    for suffix in flow_rules.FILE_KEY_SUFFIXES:
        if filename.endswith(suffix):
            return filename[: -len(suffix)]
    return filename.rsplit(".", 1)[0] if "." in filename else filename


def _when_refs(when: str) -> list[str]:
    """Every reference inside a `when:` string.

    No grammar check here, deliberately. `when:` has four rails — a compound
    boolean expression, a standalone `==`/`!=` comparison with lenient
    equality, a bare ref that is truth-tested, and a plain truthy literal —
    and which one a string takes is decided legacy-first by the server's own
    `routes_to_expression`. Mirroring that offline means reimplementing the
    predicate parser, and a near-miss reimplementation is a false-positive
    generator: the old rule here ("exactly one comparison, no boolean
    operators") rejected 55 `when:` clauses across the five shipped backend
    templates, every one of them valid.

    So the checker checks what it can check without a parser — that the paths
    named actually resolve — and leaves the grammar to `flow validate`, which
    calls the real one.
    """
    return _EMBEDDED_REF_RE.findall(_QUOTED_RE.sub("", when))


def _walk_strings(node: Any, path: str) -> list[tuple[str, str]]:
    """Every string leaf under `node`, with a dotted path to each."""
    out: list[tuple[str, str]] = []
    if isinstance(node, str):
        out.append((path, node))
    elif isinstance(node, dict):
        for key, value in node.items():
            out.extend(_walk_strings(value, f"{path}.{key}"))
    elif isinstance(node, list):
        for i, value in enumerate(node):
            out.extend(_walk_strings(value, f"{path}.{i}"))
    return out


def check_bundle(directory: str | Path) -> BundleReport:
    """Run every offline structural check over a template bundle directory."""
    path = Path(directory)
    report = BundleReport(directory=str(path))
    if not path.exists():
        report.findings.append(Finding(ERROR, "bundle-not-found", str(path), "No such directory."))
        return report
    if not path.is_dir():
        report.findings.append(
            Finding(ERROR, "bundle-not-a-directory", str(path), "Not a directory.")
        )
        return report
    return _Checker(path).run()
